#!/usr/bin/env python3

import sys

sys.path += ['linuxautomaton', 'lttnganalyses', 'lttnganalysescli']

import lttnganalysescli.syscallstats


if __name__ == '__main__':
    lttnganalysescli.syscallstats.run()
